CXX_FLAGS = -std=c++11 -I../

build: 
	g++ ${CXX_FLAGS} -c polygon.cpp -o bin/polygon.o
	g++ ${CXX_FLAGS} -c editable_polygon.cpp -o bin/editable_polygon.o
	g++ ${CXX_FLAGS} -c subdiv_window.cpp -o bin/subdiv_window.o
	g++ ${CXX_FLAGS} -c main.cpp -o bin/main.o